version: '3'

services:
  fastapi-chatbot:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge